const translations = {
  en: {
    "nav.projects":"Projects","nav.studies":"Studies","nav.about":"About","nav.contact":"Contact",
    "hero.eyebrow":"TECHNICAL ARTIST / REAL-TIME","hero.sub":"","hero.view":"View selected work","hero.contact":"Get in touch ↗","hero.caption":"Rurikoin / UE5",
    "intro.label":"SELECTED WORK","intro.title":"Building real-time worlds<br>from asset to engine.","intro.text":"I work across environment art, materials, foliage, character assets and Unreal Engine implementation.",
    "common.role":"ROLE","common.contribution":"CONTRIBUTION","common.tools":"TOOLS","common.pipeline":"PIPELINE","common.notes":"NOTES",
    "p1.title":"Rurikoin","p1.type":"Individual","p1.role":"Environment Artist / Technical Artist","p1.contribution":"Full environment, materials, foliage, SpeedTree, lighting, rain effect, glass rain shader and post processing.","p1.material.title":"Material showcase","p1.material.text":"Selected leaf, stone, wood and fabric materials authored for the environment.","p1.speed.title":"Foliage and seasonal control","p1.speed.text":"Trees were authored in SpeedTree and integrated into the environment. The project also explores foliage variation and seasonal controls.","p1.rain.title":"Dynamic rain on glass","p1.rain.text":"The environment uses Ultra Dynamic Sky to build the weather environment; the dynamic rain effect on the glass was created with custom Unreal material nodes.","p1.video":"Environment rain / final video render",
    "p2.title":"MetaHuman Character","p2.type":"Individual","p2.role":"Character Artist / Technical Artist","p2.contribution":"MetaHuman-based re-sculpting, skin texture work, Marvelous Designer clothing, cloth material authoring and Unreal implementation.","p2.cloth.title":"Two-UV clothing material setup","p2.cloth.text":"The clothing material combines Unreal Engine and Substance Designer workflows. Separate UV sets are used to control lace, background patterns and anisotropy.",
    "p3.title":"ASCEND","p3.type":"Individual","p3.role":"Environment Artist / Technical Artist","p3.contribution":"Environment assembly, level art, landscape creation, material blending, foliage setup, SpeedTree trees, lighting and post processing.","p3.notes":"Stone and statue environment assets use third-party model packs, with Ultra Dynamic Sky, the UE Water plugin and Easy Fog used for environment setup.","p3.foliage.title":"Landscape and foliage systems","p3.foliage.text":"Custom landscape blending and foliage material work were used to shape the environment. Stone assets were sourced from a third-party pack, with custom material treatment authored for the project.","p3.video":"ASCEND environment / final video",
    "studies.label":"TECHNICAL STUDIES","studies.title":"Selected studies & additional work.","studies.text":"Independent practice works are presented here.","study.h.title":"Houdini Procedural Tower Study","study.h.text":"Houdini procedural tower exercise.","study.s.title":"Substance Designer Material Study","study.s.text":"Substance Designer material exercise.","study.md.title":"MD Clothing Practice","study.md.text":"Marvelous Designer clothing practice with garment construction and presentation.","study.c.title":"Real-time Asset Studies","study.c.text":"Standard PBR workflow + AI-assisted. High-poly assets were created using ZBrush and AI, retopologized in Maya, ID maps and high-poly bakes were handled in Marmoset, clothing materials were created in Substance Painter and Substance Designer, anisotropy was implemented in Unreal Engine, and hair cards were created using the GS plugin.","study.p.title":"PLAGUE — Card Game","study.p.text":"A pre-graduate-school game design project combining illustration, UI, card design and gameplay documentation.",
    "additional.label":"WEAPON STUDY","additional.title":"Axe Asset Study","additional.text":"","additional.sd.title":"","additional.sd.text":"","additional.axe.pendingTitle":"","additional.axe.pendingText":"",
    "about.label":"ABOUT","about.title":"","about.text":"I am a Technical Art graduate student at the University of Utah with a background in game development. My work sits between environment art, materials, character assets and Unreal Engine implementation.","about.ms":"M.S. Technical Art · Graduate Student","about.bs":"B.S. Game Development","contact.label":"CONTACT","contact.title":"","footer":"Technical Artist Portfolio","detail.open":"OPEN BREAKDOWN ↗"
  },
  zh: {
    "nav.projects":"项目","nav.studies":"技术练习","nav.about":"关于我","nav.contact":"联系方式","hero.eyebrow":"技术美术 / 实时渲染","hero.sub":"","hero.view":"查看精选项目","hero.contact":"联系我 ↗","hero.caption":"琉璃光院 / UE5",
    "intro.label":"精选项目","intro.title":"从资产制作到引擎落地，<br>构建实时世界。","intro.text":"我的工作覆盖环境美术、材质、植被、角色资产以及 Unreal Engine 实现。","common.role":"职责","common.contribution":"个人贡献","common.tools":"软件 / 工具","common.pipeline":"制作流程","common.notes":"项目说明",
    "p1.title":"琉璃光院","p1.type":"个人项目","p1.role":"环境美术 / 技术美术","p1.contribution":"独立完成完整场景、材质、植被、SpeedTree、灯光、雨水效果、玻璃动态雨水材质以及后期处理。","p1.material.title":"材质展示","p1.material.text":"展示为琉璃光院场景制作的树叶、石头、木头与织物材质。","p1.speed.title":"植被与季节控制","p1.speed.text":"场景中的树木使用 SpeedTree 制作并接入环境，同时探索了植被变化与季节控制。","p1.rain.title":"玻璃上的动态雨水","p1.rain.text":"场景使用 Ultra Dynamic Sky 构建天气环境；玻璃上的动态雨水效果则使用自定义 Unreal 材质节点制作。","p1.video":"场景雨水 / 最终视频渲染",
    "p2.title":"MetaHuman 女性角色","p2.type":"个人项目","p2.role":"角色美术 / 技术美术","p2.contribution":"基于 MetaHuman 进行角色重雕、皮肤纹理绘制，使用 Marvelous Designer 制作服装，并完成服装材质与 Unreal Engine 落地。","p2.cloth.title":"双 UV 服装材质方案","p2.cloth.text":"服装材质结合 Unreal Engine 与 Substance Designer 流程，通过两套 UV 分别控制蕾丝、底纹与各向异性等效果。",
    "p3.title":"ASCEND","p3.type":"个人项目","p3.role":"环境美术 / 技术美术","p3.contribution":"负责场景组装、地编、Landscape、材质混合、植被设置、SpeedTree 树木、灯光以及后期处理。","p3.notes":"石头，雕像环境资产使用第三方模型包，使用 Ultra Dynamic Sky、UE Water plugin 与 Easy Fog进行环境制作。","p3.video":"ASCEND 场景 / 最终视频","p3.foliage.title":"Landscape 与植被材质","p3.foliage.text":"通过自定义 Landscape 混合与植被材质塑造环境。石头模型来自第三方资源包，但针对项目重新制作了材质。",
    "studies.label":"技术练习","studies.title":"精选练习与其他作品。","studies.text":"独立练习作品展示。","study.h.title":"houdini程序化塔楼练习","study.h.text":"houdini程序化塔楼练习。","study.s.title":"Substance Designer 材质练习","study.s.text":"Substance Designer 材质练习。","study.md.title":"MD服装练习","study.md.text":"Marvelous Designer 服装制作练习。","study.c.title":"实时服装 / 头发练习","study.c.text":"标准PBR流程+AI辅助。使用ZB和AI制作了高模，用Maya进行了重拓扑，八猴进行ID贴图和高模的烘焙，SP与SD制作服装的材质。导入UE处理各向异性。头发使用GS插件制作插片毛发。","study.p.title":"PLAGUE — 桌游卡牌项目","study.p.text":"研究生申请阶段的游戏设计作品，结合插画、UI、卡牌设计和游戏机制文档。",
    "additional.label":"武器练习","additional.title":"战斧资产练习","additional.text":"","additional.sd.title":"","additional.sd.text":"","additional.axe.pendingTitle":"","additional.axe.pendingText":"",
    "about.label":"关于我","about.title":"","about.text":"我目前就读于犹他大学 Technical Art 研究生项目，本科同样毕业于犹他大学游戏开发专业。我的工作位于环境美术、材质、角色资产和 Unreal Engine 实现之间。","about.ms":"Technical Art 硕士 · 在读","about.bs":"游戏开发本科","contact.label":"联系方式","contact.title":"","footer":"技术美术作品集","detail.open":"查看项目拆解 ↗"
  }
};

const details = {
  rurikoin:{kicker:'ENVIRONMENT / TECH ART',en:{title:'Rurikoin',lead:'An individual UE5 environment project focused on foliage, material authoring, SpeedTree integration, weather effects and scene presentation.'},zh:{title:'琉璃光院',lead:'个人 UE5 环境项目，重点展示植被、材质、SpeedTree 接入、天气效果以及完整场景表现。'},blocks:[
    ['FOLIAGE','p1.speed.title','p1.speed.text',['assets/japanese/speedtree-season.webp','assets/japanese/leaf-render.webp','assets/japanese/speedtree-branch.webp','assets/japanese/leaf-speedtree.webp']],
    ['MATERIAL SHOWCASE','p1.material.title','p1.material.text',['assets/japanese/leaf-material.webp','assets/japanese/stone-material.webp','assets/japanese/wood-material.webp','assets/japanese/fabric-material.webp']],
    ['RAIN / SHADER','p1.rain.title','p1.rain.text',['assets/japanese/glass-rain-shader.webp']],
    ['FINAL ENVIRONMENT','', '',['assets/japanese/hero-01.webp','assets/japanese/hero-02.webp','assets/japanese/hero-03.webp']]
  ]},
  character:{kicker:'CHARACTER / TECH ART',en:{title:'MetaHuman Character',lead:'Character asset work combining MetaHuman, ZBrush, Marvelous Designer, hair, material authoring and Unreal Engine implementation.'},zh:{title:'MetaHuman 女性角色',lead:'结合 MetaHuman、ZBrush、Marvelous Designer、头发、材质制作与 Unreal Engine 落地的角色资产项目。'},blocks:[
    ['CHARACTER','p2.role','p2.contribution',['assets/metahuman/hero-01.webp','assets/metahuman/hero-02.webp','assets/metahuman/wrap-process.webp','assets/metahuman/facial-control.webp']],
    ['CLOTH / MATERIAL','p2.cloth.title','p2.cloth.text',['assets/metahuman/fabric-detail.webp','assets/metahuman/fabric-01.webp','assets/metahuman/fabric-02.webp','assets/metahuman/cloth-ue-01.webp','assets/metahuman/cloth-ue-02.webp']],
    ['HAIR / FINAL','', '',['assets/metahuman/hair-01.webp','assets/metahuman/hair-02.webp']]
  ]},
  ascend:{kicker:'ENVIRONMENT / TECH ART',en:{title:'ASCEND',lead:'An environment-focused project combining level art, landscape materials, foliage, SpeedTree, lighting and post processing, with third-party assets clearly disclosed.'},zh:{title:'ASCEND',lead:'以环境制作与实时落地为重点，包含地编、Landscape 材质、植被、SpeedTree、灯光与后期，并明确标注第三方资源。'},blocks:[
    ['ENVIRONMENT','p3.contribution','p3.contribution',['assets/ascend/hero-01.webp','assets/ascend/hero-02.webp','assets/ascend/hero-03.webp']],
    ['LANDSCAPE / FOLIAGE','p3.foliage.title','p3.foliage.text',['assets/ascend/process-01.webp','assets/ascend/process-02.webp','assets/ascend/process-03.webp','assets/ascend/environment-breakdown.webp']],
    ['VIDEO','p3.video','p3.video',['assets/ascend/ascend-video.mp4']]
  ]},
  houdini:{kicker:'TECHNICAL STUDY',en:{title:'Houdini Procedural Tower Exercise',lead:'Houdini procedural tower exercise.'},zh:{title:'houdini程序化塔楼练习',lead:'houdini程序化塔楼练习。'},blocks:[['HOUDINI STUDY','study.h.title','study.h.text',['assets/studies/houdini-01.webp','assets/studies/houdini-02.webp']]]},
  sd:{kicker:'TECHNICAL STUDY',en:{title:'Substance Designer Material Study',lead:'Substance Designer material exercise.'},zh:{title:'Substance Designer 材质练习',lead:'Substance Designer 材质练习。'},blocks:[['SUBSTANCE DESIGNER','study.s.title','study.s.text',['assets/studies/sd-01.webp','assets/studies/sd-02.webp','assets/studies/sd-gold.webp','assets/studies/sd-stone.webp']]]},
  mdcloth:{kicker:'CLOTHING / MARVELOUS DESIGNER',en:{title:'MD Clothing Practice',lead:'Marvelous Designer clothing practice focused on garment construction and final presentation.'},zh:{title:'MD服装练习',lead:'使用 Marvelous Designer 进行服装制作与最终表现的专项练习。'},blocks:[['GARMENT PROCESS','study.md.title','study.md.text',['assets/studies/md-cloth/process-01.jpg','assets/studies/md-cloth/process-02.jpg','assets/studies/md-cloth/process-03.jpg']],['FINAL CLOTHING','','',['assets/studies/md-cloth/final-01.jpg','assets/studies/md-cloth/final-02.jpg']]]},
  cloth:{kicker:'TECHNICAL STUDY',en:{title:'Real-time Asset Studies',lead:'Real-time clothing, hair and material implementation practice.'},zh:{title:'实时服装 / 头发练习',lead:'实时服装、头发与材质落地相关的专项练习。'},blocks:[['CLOTH / HAIR','study.c.title','study.c.text',['assets/studies/cloth_render_UE.png','assets/studies/cloth_render_UE2.png','assets/studies/cloth-lowpoly.webp','assets/studies/cloth-sp.webp','assets/studies/hair-lowpoly.webp','assets/studies/cloth-sd-node.png']]]},
  axe:{kicker:'WEAPON / TEXTURE',en:{title:'Axe Asset Study',lead:'A focused weapon asset exercise covering high-poly sculpting, low-poly topology, texture authoring and Unreal Engine presentation.'},zh:{title:'战斧资产练习',lead:'独立武器资产练习，展示高模、低模拓扑、材质制作以及 Unreal Engine 最终表现。'},blocks:[['WEAPON / TEXTURE','additional.title','', ['assets/additional/axe-final-render.png','assets/additional/axe-highpoly.png','assets/additional/axe-lowpoly.png','assets/additional/axe-sp-texture.png']]],},
  plague:{kicker:'OTHER WORK',en:{title:'PLAGUE — Card Game',lead:'A pre-graduate-school game design project combining illustration, UI, card design and gameplay documentation.'},zh:{title:'PLAGUE — 桌游卡牌项目',lead:'研究生申请阶段的游戏设计作品，结合插画、UI、卡牌设计和游戏机制文档。'},blocks:[['FULL PROJECT DOCUMENTATION','','',['assets/studies/plague-ec00ee8961334a8f1fed45619fd6448a.jpg','assets/studies/plague-b4dca447d548ba3bea059b54aa2cb4c7.jpg','assets/studies/plague-03b0947b28039bf3e738f5e50a857054.jpg','assets/studies/plague-56e8b4da99a91f603fccc1ba9e86ef3b.jpg','assets/studies/plague-76d5842715931e5187abc8cab7f1cf0c.jpg','assets/studies/plague-7808136003809740d70a170606c4dd78.jpg','assets/studies/plague-dd592e839271f8f7f216458428d53c67.jpg','assets/studies/plague-27ea098127ce77e266d909fcd7068943.jpg','assets/studies/plague-e30aef8d2b5d02c5e405ce92eb6a16ab.jpg']]]}
};

let lang = localStorage.getItem('portfolio-lang') || 'en';
const btn=document.getElementById('langBtn');
function applyLang(){document.documentElement.lang=lang==='zh'?'zh-CN':'en';document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(translations[lang][k]!==undefined)el.innerHTML=translations[lang][k]});btn.textContent=lang==='en'?'中文':'EN';localStorage.setItem('portfolio-lang',lang)}
btn.addEventListener('click',()=>{lang=lang==='en'?'zh':'en';applyLang()});

const modal=document.getElementById('detailModal');
const content=document.getElementById('detailContent');
function openDetail(id){const d=details[id];if(!d)return;const copy=d[lang];let html=`<div class="detail-kicker">${d.kicker}</div><h2>${copy.title}</h2><p class="detail-lead">${copy.lead}</p><div class="detail-meta"><span>${lang==='zh'?'点击图片可放大':'Click images to enlarge'}</span><span>${lang==='zh'?'项目拆解':'Project breakdown'}</span></div>`;for(const [tag,titleKey,textKey,imgs] of d.blocks){const title=titleKey?(translations[lang][titleKey]||titleKey):'';const text=textKey?(translations[lang][textKey]||''):'';html+=`<section class="detail-block"><div><span class="mini-label">${tag}</span>${title?`<h3>${title}</h3>`:''}${text?`<p>${text}</p>`:''}</div><div class="detail-images ${imgs.length===1?'single':''}">${imgs.map(src=>src.toLowerCase().endsWith('.mp4')?`<video src="${src}" controls playsinline preload="metadata" class="detail-video"></video>`:`<img src="${src}" alt="${copy.title}" data-detail-image>`).join('')}</div></section>`}html+=`<p class="detail-footer-note">${lang==='zh'?'这是项目详情视图。返回后可继续浏览其他项目。':'Project detail view. Close this panel to continue browsing.'}</p>`;content.innerHTML=html;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';content.querySelectorAll('img').forEach(img=>img.addEventListener('click',()=>openLightbox(img.src,img.alt)))}
function closeDetail(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}
document.querySelectorAll('[data-detail]').forEach(el=>el.addEventListener('click',e=>{if(e.target.closest('img'))return;openDetail(el.dataset.detail)}));
document.querySelector('.detail-close').addEventListener('click',closeDetail);modal.addEventListener('click',e=>{if(e.target===modal)closeDetail()});

const lightbox=document.getElementById('lightbox');const lightboxImage=document.getElementById('lightboxImage');
function openLightbox(src,alt=''){lightboxImage.src=src;lightboxImage.alt=alt;lightbox.classList.add('open');lightbox.setAttribute('aria-hidden','false')}
function closeLightbox(){lightbox.classList.remove('open');lightbox.setAttribute('aria-hidden','true')}
document.querySelectorAll('img').forEach(img=>{if(img.closest('.lightbox')||img.hasAttribute('data-detail-image'))return;img.addEventListener('click',()=>openLightbox(img.currentSrc||img.src,img.alt||'Portfolio image'))});
document.querySelector('.lightbox-close').addEventListener('click',closeLightbox);lightbox.addEventListener('click',e=>{if(e.target===lightbox)closeLightbox()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeLightbox();closeDetail()}});
applyLang();
